### ISSUE TITLE
Colour coding needs to be stripped from logfile writes

### ISSUE THREAD

**Issue by MaxWasUnavailable** [LethalCompany/LCAPI.Core#33]
**Describe the bug**
Log files have the &... colour codes added. This makes readability harder.

**To Reproduce**
1. Start game
2. Check log

**Expected behavior**
No colour codes in the log file.

**Actual behavior**
Colour codes in the log file.

**Comment by Redforce04** [comment]
Interesting, as we should have a completely separate parser for logfiles. Maybe it got lost to time or isn't patching right? Or maybe the parser isn't actually stripping the color codes.
